services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: your-username
      POSTGRES_DB: coffee-shop
      POSTGRES_PASSWORD: your-password
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"