spring:
  application:
    name: concept-coffee-shop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
        ddl-auto: none # do not automatically create or update the schema
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: none
      password: none

springdoc:
  swagger-ui:
    path: /docs # the URL path to access the Swagger UI

jwt:
  secret: ${JWT_SECRET}