spring:
  application:
    name: concept-coffee-shop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql:${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      #ddl-auto: create-drop # this recreates the database on each startup, not recommended for production
      ddl-auto: update # create the tables if they don't exist automatically when the application starts
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

springdoc:
  swagger-ui:
    path: /docs # the URL path to access the Swagger UI

jwt:
  secret: ${JWT_SECRET}